name: CI
on: push

jobs:
  windows:
    runs-on: windows-2025-vs2026

    steps:
      - shell: cmd
        run: |
          where dumpbin
          echo ok

      - name: Configure Developer Command Prompt for Microsoft Visual C++
        uses: ilammy/msvc-dev-cmd@v1

      - shell: cmd
        run: where dumpbin
