name: CI
on: push

jobs:
  windows:
    runs-on: windows-2025-vs2026

    steps:
      # - shell: cmd
      #   run: |
      #     where dumpbin
      #     echo ok

      - run: |
          dir "C:\Program Files\Microsoft Visual Studio\18\Enterprise\VC"
          dir "C:\Program Files\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary"
          dir "C:\Program Files\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary\Build"

      # https://learn.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-180#use-the-developer-tools-in-an-existing-command-window
      - shell: cmd
        run: |
          "C:\Program Files\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
          where dumpbin

      # %comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64_arm uwp -vcvars_ver=14.29

      # - name: Configure Developer Command Prompt for Microsoft Visual C++
      #   uses: ilammy/msvc-dev-cmd@v1

      # - shell: cmd
      #   run: where dumpbin
